[package]
name = "holtha"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[features]
default = ["full"]
full = ["core", "sys", "gfx", "math", "input", "net", "audio"]

# Módulos opcionales
core = ["dep:holtha-core-errors", "dep:holtha-core-types", "dep:holtha-core-utils"]
sys = ["dep:holtha-sys-fs", "dep:holtha-sys-mem", "dep:holtha-sys-info"]
gfx = ["dep:holtha-gfx-window", "dep:holtha-gfx-render", "dep:holtha-gfx-color"]
math = ["dep:holtha-math-vec", "dep:holtha-math-mat", "dep:holtha-math-geo"]
input = ["dep:holtha-input-key", "dep:holtha-input-mouse", "dep:holtha-input-pad"]
net = ["dep:holtha-net-tcp", "dep:holtha-net-udp"]
audio = ["dep:holtha-audio-decode", "dep:holtha-audio-mix", "dep:holtha-audio-play"]

[dependencies]
# Core
holtha-core-errors = { path = "../core/holtha-core-errors", optional = true }
holtha-core-types = { path = "../core/holtha-core-types", optional = true }
holtha-core-utils = { path = "../core/holtha-core-utils", optional = true }

# Sys
holtha-sys-fs = { path = "../sys/holtha-sys-fs", optional = true }
holtha-sys-mem = { path = "../sys/holtha-sys-mem", optional = true }
holtha-sys-info = { path = "../sys/holtha-sys-info", optional = true }

# Gfx
holtha-gfx-window = { path = "../gfx/holtha-gfx-window", optional = true }
holtha-gfx-render = { path = "../gfx/holtha-gfx-render", optional = true }
holtha-gfx-color = { path = "../gfx/holtha-gfx-color", optional = true }

# Math
holtha-math-vec = { path = "../math/holtha-math-vec", optional = true }
holtha-math-mat = { path = "../math/holtha-math-mat", optional = true }
holtha-math-geo = { path = "../math/holtha-math-geo", optional = true }

# Input
holtha-input-key = { path = "../input/holtha-input-key", optional = true }
holtha-input-mouse = { path = "../input/holtha-input-mouse", optional = true }
holtha-input-pad = { path = "../input/holtha-input-pad", optional = true }

# Net
holtha-net-tcp = { path = "../net/holtha-net-tcp", optional = true }
holtha-net-udp = { path = "../net/holtha-net-udp", optional = true }

# Audio
holtha-audio-decode = { path = "../audio/holtha-audio-decode", optional = true }
holtha-audio-mix = { path = "../audio/holtha-audio-mix", optional = true }
holtha-audio-play = { path = "../audio/holtha-audio-play", optional = true }